services:
  - type: static_site
    name: pg-crm-frontend
    env: node
    region: oregon
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    branch: main